name: fire_base_tutorial
description: A new Flutter project.

publish_to:


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  google_fonts: ^5.0.0
  cloud_firestore: ^4.8.0
  shared_preferences: ^2.1.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/watch.png

